[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/admin/*"
  to = "/admin-dashboard.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = true